version: '3.8'
services:
  mosic_api:
    container_name: mosic_api
    build:
      context: ./
      dockerfile: ./ci/api/Dockerfile
      target: api
    volumes:
      - ./data:/app/data
    command: npm run serve:api
    ports:
      - "${API_PORT}:8888"
  mosic:
    container_name: mosic
    build:
      context: ./
      dockerfile: ./ci/api/Dockerfile
      target: web
    volumes:
      - ./src:/app/src
      - ${MUSIC_PATH}:/app/src/music
    command: npm run serve:web
    ports:
      - "${WEB_PORT}:8080"
  cli:
    build:
      context: ./
      dockerfile: ./ci/api/Dockerfile
      target: cli
    profiles: ['cli']
    volumes:
      - ./data:/app/data
      - ${MUSIC_PATH}:/app/src/music
    command: node walker walk
  cli_init:
    build:
      context: ./
      dockerfile: ./ci/api/Dockerfile
      target: cli
    profiles: ['cli']
    volumes:
      - ./data:/app/data
      - ${MUSIC_PATH}:/app/src/music
    command: node walker init
